* pmxtricks
This package provides shortcuts and tricks in the everyday work as a
pharmacometrician working with R and Nonmem. Not all functionality in
the package is stable at this point. When that said, a lot is, and it
contains very useful things. The package is mostly written using the
incredibly fast data.table package.

** A universal nonmem data reader
One function the author has not been able to find anywhere else is
called NMscanData. It automatically finds and reads tables generated
by Nonmem, merges with input data (the data submitted to Nonmem), and
creates a standardised representation at four levels of variability:
population (model run), subject, subject-occasion, and row. A separate
vignette is under development this function.

** Create data, export to Nonmem, read results
These are the steps that this package especially helps with. Here are some hightlights:

flagsAssign - Assign exclusion flags to a dataset based on specified table

flagsCount - Create an overview of number of retained and discarded datapoints.

NMorderColumns - Order columns in dataset for use in Nonmem.

NMwriteData - Write dataset (with creation info documentation) for use in Nonmem (and R)

NMscanData - automatically find Nonmem input and output tables and organize data

metadata function for documentation of column contents is under development.

** Analyze nonmem results
ggIndProfs - Plot individual profiles and doses based on NM style dataset data

NMrunLog - get an overview of your Nonmem runs

** Edit nonmem runs
NMgetSection - extract sections of Nonmem control streams

NMreplacePart - replace ($)sections of a nonmem control stream


** Create simulation code in R
NMcode2R - Translate NM $PK section or other Nonmem code to R code

genCovFun - create R function that generates param values based on covariates

** Handy data wrangling tools
findCovs - Extract columns that do not vary within variables in a data.frame

findVars - Extract columns that vary within values of other columns in a data.frame

mergeCheck - Merge, order, and check resulting rows and columns.
