* pmxtricks
This package provides shortcuts and tricks in the everyday work as a
pharmacometrician working with R and Nonmem. Not all functionality in
the package is stable at this point. When that said, a lot is, and it
contains very useful things. The package is mostly written using the
incredibly fast data.table package.

** Analyze nonmem results
ggIndProfs - Plot individual profiles and doses based on NM style dataset data

NMrunLog - get an overview of your Nonmem runs

** Edit nonmem runs
NMgetSection - extract sections of Nonmem control streams

NMreplacePart - replace ($)sections of a nonmem control stream (update multiple
nonmem control streams simultaneously).


** Create simulation code in R
NMcode2R - Translate NM $PK section or other Nonmem code to R code

genCovFun - create R function that generates param values based on covariates

** Handy data wrangling tools
findCovs - Extract columns that do not vary within variables in a data.frame

findVars - Extract columns that vary within values of other columns in a data.frame

mergeCheck - Merge, order, and check resulting rows and columns.
